version: "3.8"

services:

  postgres:
    image: postgres:14
    restart: unless-stopped
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/

  node:
    image: node
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - proxy
      - default
    env_file:
      - .env
    working_dir: /home/node/app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./src/:/home/node/app:rw
    ports:
      - 8083:3000
    command: "npm start"

networks:
  proxy:
    external: true
